### ISSUE TITLE
Provide for composer installation

### ISSUE THREAD

**Issue by bradjones1** [pitbulk/moodle_saml#50]
Theoretically we could do this with the [composer installer](https://raw.githubusercontent.com/composer/installers/master/src/Composer/Installers/MoodleInstaller.php), however this package provides both an auth and enrol plugin. Perhaps we could whip up a quick custom installer?

**Comment by pitbulk** [comment]
I think is a good idea to add this functionality.
I keep auth and enroll in the same repo because enroll depends of auth and for me is easier for maintain, but you can see that in Moodle, there are 2 different plugins and each has its own place:
* https://moodle.org/plugins/auth_saml
* https://moodle.org/plugins/enrol_saml

So what is your suggestion?

**Comment by bradjones1** [comment]
@pitbulk My suggestion would actually be to do a subtree split and have a separate repo for each of these. Partly because it would be easier to have them installable via composer (and one can require the other) but also that it would be easier to integrate with travis for CI, since it's looking for a version.php at the top-level of the repo. Does that sound OK for you?

**Comment by pitbulk** [comment]
Ok, I will try to create 2 new repos, update Moodle to reference them and set a note on this repo to reference them too.

But right now I'm quite busy so that will take time.

**Comment by bradjones1** [comment]
@pitbulk I've created a new moodle-saml organization and added you to it, with repos for the subtree splits. I will seed those, shortly.

**Comment by pitbulk** [comment]
Ok, perfect if you can take care of that part.
